# # Generated by Django 3.0 on 2022-06-13 11:22
#
# from django.db import migrations, models
# import django.db.models.deletion
# import jsonfield.fields
# import scraping.models
#
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = [
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='City',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=50, unique=True, verbose_name='City name')),
#                 ('slug', models.SlugField(blank=True, unique=True)),
#             ],
#             options={
#                 'verbose_name': 'City name',
#                 'verbose_name_plural': 'Cities names',
#             },
#         ),
#         migrations.CreateModel(
#             name='Error',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('data', jsonfield.fields.JSONField(default=dict)),
#                 ('timestamp', models.DateField(auto_now_add=True)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='ProgramLanguage',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=50, unique=True, verbose_name='Programming language')),
#                 ('slug', models.SlugField(blank=True, unique=True)),
#             ],
#             options={
#                 'verbose_name': 'Programming language',
#                 'verbose_name_plural': 'Programming languages',
#             },
#         ),
#         migrations.CreateModel(
#             name='Vacancy',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('url', models.URLField(unique=True)),
#                 ('title', models.CharField(max_length=250, verbose_name='Title')),
#                 ('company', models.CharField(max_length=250, verbose_name='Company')),
#                 ('description', models.TextField(verbose_name='Description')),
#                 ('timestamp', models.DateField(auto_now_add=True)),
#                 ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='City')),
#                 ('program_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.ProgramLanguage', verbose_name='Program language')),
#             ],
#             options={
#                 'verbose_name': 'Vacancy',
#                 'verbose_name_plural': 'Vacancies',
#             },
#         ),
#         migrations.CreateModel(
#             name='Url',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('url_data', jsonfield.fields.JSONField(default=scraping.models.default_urls)),
#                 ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='City')),
#                 ('program_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.ProgramLanguage', verbose_name='Program language')),
#             ],
#             options={
#                 'unique_together': {('city', 'program_language')},
#             },
#         ),
#     ]
