# # Generated by Django 3.0 on 2022-06-18 15:56
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('scraping', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.AlterModelOptions(
#             name='vacancy',
#             options={'ordering': ['-timestamp'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
#         ),
#     ]
