# Generated by Django 3.2 on 2022-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20220620_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=1500, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Title'),
        ),
    ]
